# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build and test
      run: |
          npm ci
          npm run build --if-present
          npm test
    - name: Backup documentation
      run: |
          cp ./README.md ./out
          cp -R ./docs ./out
    - uses: actions/checkout@v2
      with:
        ref: dist
        clean: false
    - name: Push the transpiling-output code to dist branch
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          chmod +x ./release.sh
          bash ./release.sh
